steps:
  - name: gcr.io/cloud-builders/git
    args: ["submodule", "update", "--init"]
  - name: golang:1.20.2
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -euxo pipefail
        apt-get update
        apt-get install -y jq
        make test
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        set -euxo pipefail
        docker build -t europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:${SHORT_SHA} --build-arg VERSION=${TAG_NAME} --build-arg COMMIT=${SHORT_SHA} .
        if [[ "${BRANCH_NAME}" == "master" ]]; then
          docker tag europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:{${SHORT_SHA},latest}
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:${SHORT_SHA}
          docker push europe-west2-docker.pkg.dev/$PROJECT_ID/badrobot/badrobot-cli:latest
        fi
options:
  logging: CLOUD_LOGGING_ONLY
